### PR TITLE
Add chacha20

### PR DESCRIPTION
**Pull request by tiffany352**
I've added wrappers and a test vector for ChaCha. The test vector used is from the IETF TLS draft.

### CODE REVIEW

**Comment by dnaq** [comment]
Thanks for the pull request. I'm currently reviewing your patch, but I don't find any reference to `crypto_core_chacha20` in libsodium, neither version 1.0.3 or the current github repository. Would you like to resubmit the pull request?

**Comment by burdges** [comment]
Appears chacha20 itself exists only in crypto_stream.

**Comment by tiffany352** [comment]
I was a bit confused as to the structure of this library, with all the macros everywhere. It appears I accidentally created bindings for `crypto_core_chacha20`, when the actual functions are `crypto_stream_chacha20` ( http://doc.libsodium.org/advanced/chacha20.html ). It looks like I can correct this by simply deleting the crypto_core_chacha20 file I added. The other code using `crypto_stream_chacha20` works just fine.

**Comment by dnaq** [comment]
That's no problem at all. If you have the time please fix the pull request and resubmit it and I'll merge.

**Comment by tiffany352** [comment]
I can't update this pull request with it being closed, do you really want me to submit a new pull request?

**Comment by dnaq** [comment]
Merged and rebased in 07407ca4089c8b3df69b1612ba4895e9cd33e331

**Pull request closed without merging**
