### PR TITLE
Streaming hashing interface for SHA-2

### LINKED ISSUE #119: Stream hasher
Does sodium have a stream hasher for sodiumoxide::crypto::hash / sha256?
If it does, I would like to request bindings.

### PR DESCRIPTION
**Pull request by sopium**
Fixes #119.

Mostly follows streaming HMAC interface and implementation. Difference from the HMAC part is explained in comments.

### CODE REVIEW

**Comment by defuz** [comment]
@dnaq @sopium Are there any reasons why this can not be merged?

**Comment by dnaq** [comment]
Only lack of time

**Comment by rickystewart** [comment]
+1, this would be great to finally have in master.

**Comment by dnaq** [comment]
The functionality is added, merged #175 instead of this one since it was already rebased to master. Thanks for your contribution.

**Pull request closed without merging**
