### PR TITLE
Additions for keypair conversion from ed25519 to curve25519

### PR DESCRIPTION
**Pull request by cjcole**
http://doc.libsodium.org/advanced/ed25519-curve25519.html

### CODE REVIEW

**Comment by dnaq** [comment]
Thanks for the pull request. We've had some discussion on this functionality in issue #85, and I decided to not add it until someone could present a valid use-case for the functionality. The reason being that I don't feel confident in adding something that could open up to cross-protocol attacks unless there's a real need for it from developers. Do you have a specific use-case you need?

**Comment by burdges** [comment]
Pond uses these when initializing v2 of its ratchet, but Pond is not written in Rust and it didn't need them really.  I could imagine Axolotl initialization with TripleDH might tend towards using these when you're trying to squeeze a bunch of preliminary ratchet state onto a business card QR code or something.

**Comment by dnaq** [comment]
I'm not familiar with the Pond ratchet, but AFAIK the Axolotl ratchet only uses diffie-hellman, e.g. `crypto_scalarmult()` and doesn't use public key signatures, `crypto_sign()` so there would be no need to convert between ed25519 and curve25519 key types for it. I might be wrong though, I don't know if the Axolotl ratchet has been updated since I last looked at it.

**Comment by burdges** [comment]
Pond uses Axolotl.  Imho, it's not worth going into how Pond uses these. 

Yes, Axolotl normally uses TripleDH for deniability, but there are situations where you might want full/manual ratchet initialization, like a phones initiating connectivity in physical proximity or a business card with a QR code.  Those applications benefit from a signing key that can be verified elsewhere, so they save 32 bytes using this. 

There are applications in implicit signatures like elliptic curve qu-vanstone that save 64 bytes, but that requires exposing even more.  https://en.wikipedia.org/wiki/Implicit_certificate#Generating_implicit_certificates

**Comment by dnaq** [comment]
I'm closing this issue for now since we're mostly discussing hypothetical use cases for a feature that brings with it potential for cross protocol attacks. I'm open to revisiting this issue if more concrete use-cases are found. Thanks to all of you that have brought valuable input to this issue.

**Comment by cjcole** [comment]
Just curious. It is not the case that sodiumoxide is intended to be a generic wrapper for libsodium?

**Comment by jedisct1** [comment]
sodium is a bit more opinionated.

If you are looking for a low-level, generic wrapper for libsodium, https://github.com/rustyhorde/sodium-sys and https://github.com/zonyitoo/libsodium-sys might be better options.

**Comment by cjcole** [comment]
One of those might be a better fit for me. Thanks for the links.

**Comment by dnaq** [comment]
> It is not the case that sodiumoxide is intended to be a generic wrapper for libsodium?

sodiumoxide is a bit more opinionated. Hope you find what you're looking for elsewhere. However, I asked you for a use case for the functionality you requested, but you didn't provide me one. Still if you have a specific use case that you want to discuss we could discuss it further.

**Pull request closed without merging**
