### PR TITLE
libsodium-sys: Added bindings from crypto_pwhash_scryptsalsa208sha256.h

### PR DESCRIPTION
**Pull request by actimehl**
First step for Issue #21

### CODE REVIEW

**Comment by dnaq** [comment]
Thanks, I just have two comments.
1. Why do you import c_uintXX? rusts uXX types are already of known and fixed size. (e.g. c_uint32 -> u32)
2. Some functions have pointers to arrays as arguments, however it would probably be better for the API that these functions are exposed as straight pointers, otherwise we need to do pointer casting to call them with for example slices.

**Comment by dnaq** [comment]
Will you update the pull-request or should I close it?

**Comment by actimehl** [comment]
I'll update

**Comment by actimehl** [comment]
Changed c types to rust ones if its unambiguous.
And it's now impossible to see, that crypto_pwhash_scryptsalsa208sha256_str expects a fix size array and not a null terminated c-string.

**Comment by dnaq** [comment]
Thanks. u8, u16, et. al are well defined in the rust documentation, so I'm not worried about that at all. In regards to the fixed size array, if you're sure that rust compiles '*mut u8' to the same thing as '*mut [u8; SIZE]' (and even better, show where that is documented) then I might change all ffi-functions that take fixed length arguments (and replace all calls to 'as_ptr()' with as '*[u8; SIZE]').

**Comment by actimehl** [comment]
In c `void function(char *data);` and `void function(char data[10]);` are the same. But the second declaration tells what the function expects. In c one can call `function` in both cases with any array or pointer and the compiler won't bother.

But rust will take the hint and stop you from calling `function` with an array of wrong size. Look at [rust playpen](http://is.gd/ePibAZ) and compile to asm to see, that both calls are compiled to the same asm. See also https://github.com/actimehl/c_ffi_test

**Comment by dnaq** [comment]
I updated all other code in libsoidum-sys to take fixed-length arrays where possible as well.

**Pull request merged**
