### PR TITLE
Add stream_xor_ic functions and Use vec! instead of repeat

### PR DESCRIPTION
**Pull request by quininer**
:)

### CODE REVIEW

**Comment by quininer** [comment]
`Repeat` is very slow, using `vec!` instead of it, will have a considerable performance boost.

before:
screenshot_20170712_192546

after:
screenshot_20170712_192535

**Comment by zonyitoo** [comment]
@dnaq Can you review this PR?

**Comment by dnaq** [comment]
Can you split this into two different pull requests?

**Comment by dnaq** [comment]
I kept the pr open since I haven’t added the _ic functions yet. Do you want me to reopen the issue?

**Comment by quininer** [comment]
It has a two years ago [issue](https://github.com/dnaq/sodiumoxide/issues/80)

**Pull request closed without merging**
