### PR TITLE
Unbreak Build

### PR DESCRIPTION
**Pull request by naftulikay**
Do it for the internet points.

### CODE REVIEW

**Comment by dnaq** [comment]
In what way does your patch unbreak the build? I can run all tests on nightly as of now, is there any specific case where the nightly build breaks?

**Comment by naftulikay** [comment]
Master has a red badge. Make sure to clear your cache.

**Comment by dnaq** [comment]
I fixed the underlying issue instead. Thanks for bringing it to my attention.

**Comment by naftulikay** [comment]
👍

**Pull request closed without merging**
